[package]
name = "sre-engine"
version = "0.1.0"
authors = ["Kangzhi Shi <shikangzhi@gmail.com>", "RustPython Team"]
description = "A low-level implementation of Python's SRE regex engine"
repository = "https://github.com/RustPython/sre-engine"
license = "MIT"
edition = "2018"
keywords = ["regex"]

[dependencies]
num_enum = "0.5"
bitflags = "1.2"
